### ISSUE TITLE
annoying bug in setup.py

### ISSUE THREAD

**Issue by davidedelvento** [soravux/scoop#16]
When installing `scoop` with its `setup.py` it requests `argparse>=1.1` in `install_require`. That downloads and installs `arparse 1.2.1` even when using `python 2.7` which already has its own `argparse 1.1`.

This is a serious problem, because `argparse 1.2.1` is old and bugous, and after it is installed, it is used instead of the system one, causing hard-to-track-down troubles such as the one described http://stackoverflow.com/questions/29374044/

So, please change the requirements using a conditional append, e.g. 

```python
    if sys.version_info < something:
        install_requires. append('argparse>=1.1')
```

Moreover, you may want to investigate why that requirement pulls `argparse 1.2.1` when on PyPI there is `1.2.2` and `1.3` available.

**Comment by soravux** [comment]
Thanks for the report. Fixed in 39e8bd466606158db12522d9f031a878037b60bf.
