### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by sesslerp** [soravux/scoop#17]
Output of `pip install scoop`:

```
Collecting scoop
  Could not find a version that satisfies the requirement scoop (from versions: 0.7.0.release, 0.7.1.release)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external scoop to allow).
  No matching distribution found for scoop
```

Python version is 2.7.9

**Comment by joernhees** [comment]
a wild guess is that this is related to moving SCOOP from googlecode to github.
https://pypi.python.org/pypi/scoop/ links to https://code.google.com/p/scoop/downloads/list which doesn't list 0.7.0 or 0.7.1.

temporary workaround:
```
pip install https://pypi.python.org/packages/source/s/scoop/scoop-0.7.1.release.tar.gz
```

**Comment by soravux** [comment]
Hello all,

Actually, the problem is our naming policy which doesn't play well with the
new version of pip. We'll try to fix it soon.
Meanwhile, the workaround proposed by Jörn should work, thanks to him.

Have a nice day,
Yannick

**Comment by joernhees** [comment]
any ETA on this yet? at the moment it's a big turn-off for anyone new to scoop as `pip install scoop` will fail...

**Comment by SmokinCaterpillar** [comment]
``pip install scoop`` still fails. I like scoop a lot and use it often, but it would be much easier to recommend to other people if you can set it up seamlessly ;-)

**Comment by joernhees** [comment]
i'd do it, but i don't have the permissions... ;(

**Comment by soravux** [comment]
Fixed the version numbering. `pip install scoop` should work now.

**Comment by joernhees** [comment]
cool, thanks ;)
