### ISSUE TITLE
Allocation issue with SLURM

### ISSUE THREAD

**Issue by croessert** [soravux/scoop#26]
When $SLURM_JOB_NODELIST is e.g. "nodes[006,011]" I get the following error:

File "/python27/lib/python2.7/site-packages/scoop/utils.py", line 209, in parseSLURM
    bmin,bmax = rng.split('-')
ValueError: need more than 1 value to unpack

If  $SLURM_JOB_NODELIST is e.g. "nodes[021-022]" the workers are deployed over the two hosts.

**Comment by soravux** [comment]
SLURM support was added by a user, and I don't have any SLURM cluster that I can test on right now. If you are willing to add the support for the different naming convention, I'll be glad to merge your pull request. If you can assure me that the only thing that is missing is the support for the comma in the brackets, I can add it myself.

You can always use the fix of #25 to generate a hostfile beforehand (ie. at the beginning of your submit script) and launch your run using this hostfile.

**Comment by croessert** [comment]
Thanks for the tip. I solved it by using:

```shell
hosts=$(srun bash -c hostname)
python -m scoop --host $hosts script.py
```

Even adding support for the comma won't tell you if tasks have been allocated unevenly across the nodes. Maybe there is a SLURM variable that tells you the allocated tasks per node?

**Comment by croessert** [comment]
The above is not working, see my comment in #25

**Comment by soravux** [comment]
Pull request accepted, thanks.
