### ISSUE TITLE
allow BASE_SSH to be set with ssh compatible wrapper 

### ISSUE THREAD

**Issue by vplugaru** [soravux/scoop#32]
Dear Yannick,

Would it be possible to set the 'ssh' part of BASE_SSH (class Host, launch/workerLaunch.py) with an environment variable (e.g. SCOOP_SSH) if it's defined?
This is helpful in HPC environments that require the use of a wrapper around ssh (passing all arguments down to ssh).

Thank you!

**Comment by soravux** [comment]
Thanks for the feedback. I just added a flag `--ssh-executable` for this purpose on commit aab50f0ab433b1cd620c7cf2d44af185908a5053. Hope it's okay with you!

**Comment by vplugaru** [comment]
Dear Yannick,

That's perfect, thank you!

Best regards,
Valentin

-- 
Valentin Plugaru | valentin.plugaru@uni.lu
Parallel Computing and Optimization Group
CSC Research Unit, University of Luxembourg
PGP KeyID 0x324FADC2
