### ISSUE TITLE
Will scoop create a lot of overhead in clusters

### ISSUE THREAD

**Issue by mistguy** [soravux/scoop#34]
I want to run a simple script in a cluster whose network transmission rate is relatively low. Processes in my script, if created by multiprocess module, have little communication with each other.

Will scoop need a lot of IO over network during execution, which will create a lot of overhead here?

**Comment by soravux** [comment]
The bulk of the communication SCOOP does is:

1. Launching the workers through an SSH command;
2. The serialized (using the pickle module) arguments of the parallel functions.

Try serializing the arguments of your parallel functions using `pickle.dumps()`. This will be a pretty good estimation of the amount of communication performed by SCOOP.
