### ISSUE TITLE
Get list of hosts used for execution

### ISSUE THREAD

**Issue by daydreamcatcher** [soravux/scoop#35]
I'm using scoop to distribute simulation jobs. For that, i need to distribute some files to the used hosts. Is it possible to get a list of currently used hosts in execution? If i use each thread to rsync the files to the local memory, this may end id too much connections to the origin host.

Thanks ;)

**Comment by soravux** [comment]
Workers are not aware of the rest of the cluster, only of the broker. As such, they don't have any list of hosts ready-to-use.

You could however perform the same host discovery step as the launcher did, as [shown here](https://github.com/soravux/scoop/blob/baf7769889710784b813e0692f1d58d8b58b9cd8/scoop/launcher.py#L447). This will re-parse the host list (either coming from SLURM, PBS, etc.) and give you the list of hosts used for the computation.
