### ISSUE TITLE
Cannot import in Mac OS X 10.11.4

### ISSUE THREAD

**Issue by nettrino** [soravux/scoop#40]
Hello,

I apologize if this is due to some misconfiguration from my part (most likely), but I can't seem to be able to import scoop in mac os x. I get the following error

(gen) nettrino$ python
**Python 3.5.1** (default, Apr 18 2016, 11:46:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scoop
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/nettrino/projects/test/scoop.py", line 1, in <module>
**from scoop import futures**
**ImportError: cannot import name 'futures**

Here is my pip packages (I'm in a virtual environment with Python3 but same happens with Python 2)
greenlet (0.4.9)
numpy (1.11.0)
pip (8.1.1)
pyzmq (15.2.0)
scoop (0.7.1.1)
setuptools (20.9.0)
wheel (0.29.0)

nettrino$ python --version
Python 3.5.1

Any hints would be much appreciated

**Comment by soravux** [comment]
Hello,

You seem to have created a file named `scoop.py` in your current working directory. This is problematic, as Python finds this file before the SCOOP package, and believes this is the `scoop` you mean when you type `import scoop`. Just rename (or remove) this file and you should be good to go.

Hope it helps you!

**Comment by nettrino** [comment]
Indeed! Thanks a lot for the prompt reply!
