### ISSUE TITLE
Python 3 unicode TypeError in utils.py

### ISSUE THREAD

**Issue by allthedata** [soravux/scoop#46]
There is an issue in `utils.py` when both SLURM and Python 3 are used. In [line 208](https://github.com/soravux/scoop/blob/c02d0a486627ce0b9707e5fef34e4bc9e753c067/scoop/utils.py#L208), `subprocess.check_output` returns a bytestring, and then the next line the bytestring is split by a unicode string, resulting in an error. The solution is after line 208 to add the following:

``` python
if sys.version_info.major > 2:
    hostsstr = hostsstr.decode()
```

**Comment by soravux** [comment]
Thanks for the fix! It's commited in b700f5c6052fea2f27ee818b29247ece6476ef0b.
