### ISSUE TITLE
remote with different user/port

### ISSUE THREAD

**Issue by jaromrax** [soravux/scoop#48]
Hi,
  is there a way to run with different user and different port? 
When I try to give user2@xxx.xx.xx.xx -p yyyy, it ends with 
'ssh: connect to host xx.xx.xx.xx  -p yyyy port 22: Connection timed out\r\n'

And I see the commandlines like  setenv PYTHONPATH /home/user1/root/lib/:
which will not obviously work if user1 != user2

maybe there could be some local program (like in jug) that knows the local setting...
Thank you

**Comment by soravux** [comment]
The easiest way to change the user and port of diverse hosts is to set them accordingly in your ssh's config file. There, you can set the user and port on a per-host basis, and it will be transparent to SCOOP.
By the way, you can change the remote root path using the `--path` argument.
