### ISSUE TITLE
scoop confused by bashrc echo

### ISSUE THREAD

**Issue by maharjun** [soravux/scoop#53]
I have noted the following problem.

I have code in my .bashrc that echo's a status message. When ssh-ing to this machine while dispatching jobs, SCOOP appears to be confused by this message and appears unable to launch jobs on this host effectively. (I get an error message specifically mentioning the bashrc status message. From what I could see, Only one job per node could be launched in such a case. Is there any way to fix this without having to disable the status message? (The message is rather useful when sshing to the machine in other contexts). Upon disabling the output, the error message disappears and the scheduling works fine.

**Comment by maharjun** [comment]
The only solution for this that I have found is to make the bashrc print the message only if the output is a terminal.

**Comment by joernhees** [comment]
hmm, i'd say "out of scope" from a scoop perspective... your `.bashrc` should check if it's in interactive mode or not (which most do by default):
https://unix.stackexchange.com/questions/257571/why-does-bashrc-check-whether-the-current-shell-is-interactive

**Comment by soravux** [comment]
I agree with @joernhees. However, if you ever find a solution that solves the issue without drawback, pull requests are always welcome.
