### ISSUE TITLE
max tasks per child

### ISSUE THREAD

**Issue by gduffley** [soravux/scoop#58]
First off, if this isn't an appropriate place to ask a question, just let me know and feel free to delete this issue. I could't find discussion forum anywhere. 

Using pythons multiprocessing Pool class, you can specify max tasks per child to create a clean environment for each run of the function. Is there a way to do this in scoop using futures.map? 

Thanks!

**Comment by soravux** [comment]
Don't worry, it's the right place for this kind of questions.

There is currently no way to simulate the effect of the `maxtasksperchild` argument from multiprocessing's Pool. Pull requests for this matter are welcome, tough.
