### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by johann-petrak** [soravux/scoop#78]
Looks like this project did not receive any updates recently, the web page http://pyscoop.org/ which is in the description and the README redirects to some news site.
If the authors are still active on github, could they please comment on the status of the project?

**Comment by soravux** [comment]
SCOOP has done its job over the years. It is in a usable state, however I think there are now much more alternatives than when this project started. Futures and asynchronous IO are now built-in in newer Python version, and support for multiple hosts is now also available on many packages. This was not the case when this project started. It helped raise awareness on these parallel development paradigms. 

Currently, its main addition over other alternatives is the support for cluster launchers like SLURM, SGE (defunct, I think?) or PBS compatible launchers.

I sadly do not have the time to support this library any longer. I have not renewed the domain pyscoop.org , I will remove it from the README, thanks for the notification. Feel free to fork it or submit a pull request if you want to contribute.

**Comment by anandtrex** [comment]
> support for multiple hosts is now also available on many packages.

@soravux Is there a particular package you would recommend for multiple host runs? With a cursory search, I wasn't able to find something with as simple and general an interface as SCOOP.
